# Generated by Django 4.2.7 on 2026-01-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('private', '用户私信'), ('business', '业务提醒')], default='system', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联业务ID')),
                ('related_url', models.URLField(blank=True, null=True, verbose_name='关联跳转链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat', to='message.message', verbose_name='关联消息')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='message.privatechat', verbose_name='回复的消息')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '私信',
                'verbose_name_plural': '私信管理',
                'ordering': ['-message__create_time'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='message_pri_sender__813ae4_idx'), models.Index(fields=['recipient', 'sender'], name='message_pri_recipie_3bbafd_idx'), models.Index(fields=['sender'], name='message_pri_sender__82e8a6_idx'), models.Index(fields=['recipient'], name='message_pri_recipie_3c28ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'is_read', 'create_time'], name='message_mes_user_id_930f33_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'is_deleted', 'create_time'], name='message_mes_user_id_852b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'type', 'create_time'], name='message_mes_user_id_41e894_idx'),
        ),
    ]
