# Generated by Django 4.2.7 on 2026-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['sender', 'recipient'], name='message_pri_sender__813ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['recipient', 'sender'], name='message_pri_recipie_3bbafd_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['sender'], name='message_pri_sender__82e8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['recipient'], name='message_pri_recipie_3c28ea_idx'),
        ),
    ]
