# Generated by Django 4.2.7 on 2026-01-23 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='特权名称')),
                ('description', models.TextField(verbose_name='特权描述')),
                ('required_level', models.CharField(choices=[('normal', 'Ⅰ'), ('bronze', 'Ⅱ'), ('silver', 'Ⅲ'), ('diamond', 'Ⅳ'), ('king', 'Ⅴ'), ('god', 'Ⅵ')], max_length=20, verbose_name='所需VIP等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'VIP特权',
                'verbose_name_plural': 'VIP特权管理',
                'ordering': ['-required_level'],
            },
        ),
        migrations.CreateModel(
            name='VIPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='充值金额')),
                ('duration', models.IntegerField(verbose_name='充值时长(天)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'VIP充值订单',
                'verbose_name_plural': 'VIP充值订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('normal', 'Ⅰ'), ('bronze', 'Ⅱ'), ('silver', 'Ⅲ'), ('diamond', 'Ⅳ'), ('king', 'Ⅴ'), ('god', 'Ⅵ')], default='normal', max_length=20, verbose_name='VIP等级')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开通时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='续费次数')),
                ('total_recharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='累计充值金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP会员',
                'verbose_name_plural': 'VIP会员管理',
                'ordering': ['-level'],
            },
        ),
    ]
