# Generated by Django 4.2.7 on 2026-01-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已取消关注')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '关注关系',
                'verbose_name_plural': '关注关系管理',
                'indexes': [models.Index(fields=['follower', 'following', 'is_deleted'], name='user_follow_followe_21a159_idx'), models.Index(fields=['following', 'is_deleted'], name='user_follow_followi_528ff6_idx'), models.Index(fields=['follower', 'is_deleted'], name='user_follow_followe_c5e725_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('moment', '动态'), ('place', '地点')], max_length=10, verbose_name='收藏类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='收藏对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏管理',
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='unique_user_content_object'), models.Index(fields=['user', 'content_type', 'created_at'], name='user_collec_user_id_7b726f_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
