# Generated by Django 4.2.7 on 2026-01-15 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已取消关注')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '关注关系',
                'verbose_name_plural': '关注关系管理',
                'indexes': [models.Index(fields=['follower', 'following', 'is_deleted'], name='user_follow_followe_21a159_idx'), models.Index(fields=['following', 'is_deleted'], name='user_follow_followi_528ff6_idx'), models.Index(fields=['follower', 'is_deleted'], name='user_follow_followe_c5e725_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
