# Generated by Django 4.2.7 on 2026-01-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('moment', '动态'), ('place', '地点')], max_length=10, verbose_name='收藏类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='收藏对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏管理',
                'indexes': [models.Index(fields=['user', 'content_type'], name='user_collec_user_id_d99512_idx'), models.Index(fields=['user', 'created_at'], name='user_collec_user_id_b096a1_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
