# Generated by Django 4.2.7 on 2026-02-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_communityevent_report_reportstatistics_reporttype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communityevent',
            table='community_events',
        ),
    ]
