# Generated by Django 4.2.7 on 2026-01-17 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_collection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='user_collec_user_id_d99512_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='user_collec_user_id_b096a1_idx',
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='unique_user_content_object'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'content_type', 'created_at'], name='user_collec_user_id_7b726f_idx'),
        ),
    ]
