# Generated by Django 4.2.7 on 2026-02-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_communityevent_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communityevent',
            table='community_event',
        ),
    ]
