# Generated by Django 4.2.7 on 2026-01-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=1000, verbose_name='日记内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mood', models.CharField(choices=[('happy', '开心'), ('heart', '心动'), ('laugh', '欢乐'), ('sad', '难过'), ('angry', '生气'), ('calm', '平静')], default='happy', max_length=10, verbose_name='心情')),
                ('is_shared', models.BooleanField(default=False, verbose_name='是否共享')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteimage', models.ImageField(upload_to='note_images/%Y/%m/%d/', verbose_name='日记图片')),
                ('notemoment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_images', to='note.note')),
            ],
        ),
    ]
