# Generated by Django 4.2.7 on 2026-01-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=1000, verbose_name='日记内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mood', models.CharField(choices=[('happy', '开心'), ('heart', '心动'), ('laugh', '欢乐'), ('sad', '难过'), ('angry', '生气'), ('calm', '平静')], default='happy', max_length=10, verbose_name='心情')),
                ('is_shared', models.BooleanField(default=False, verbose_name='是否共享')),
                ('is_collaborative', models.BooleanField(default=False, verbose_name='是否为协同日记')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('last_edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_notes', to=settings.AUTH_USER_MODEL, verbose_name='协作者')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_notes', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteimage', models.ImageField(upload_to='note_images/%Y/%m/%d/', verbose_name='日记图片')),
                ('notemoment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_images', to='note.note')),
            ],
        ),
        migrations.CreateModel(
            name='EditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('insert', '插入'), ('delete', '删除'), ('replace', '替换')], max_length=10, verbose_name='操作类型')),
                ('content', models.TextField(verbose_name='操作内容')),
                ('position', models.IntegerField(verbose_name='操作位置')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('revision', models.IntegerField(default=1, verbose_name='版本号')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_operations', to='note.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '编辑操作',
                'verbose_name_plural': '编辑操作历史',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='note.note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='note.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日记评论',
                'verbose_name_plural': '日记评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_likes', to='note.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日记点赞',
                'verbose_name_plural': '日记点赞',
                'unique_together': {('user', 'note')},
            },
        ),
        migrations.CreateModel(
            name='CollaborativeEditingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('cursor_position', models.IntegerField(default=0, verbose_name='光标位置')),
                ('selection_start', models.IntegerField(default=0, verbose_name='选择开始位置')),
                ('selection_end', models.IntegerField(default=0, verbose_name='选择结束位置')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_sessions', to='note.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '协同编辑会话',
                'verbose_name_plural': '协同编辑会话记录',
                'unique_together': {('note', 'user')},
            },
        ),
    ]
