# Generated by Django 4.2.7 on 2026-01-11 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_notes', to=settings.AUTH_USER_MODEL, verbose_name='协作者'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_collaborative',
            field=models.BooleanField(default=False, verbose_name='是否为协同日记'),
        ),
        migrations.AddField(
            model_name='note',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AddField(
            model_name='note',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_notes', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑者'),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='EditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('insert', '插入'), ('delete', '删除'), ('replace', '替换')], max_length=10, verbose_name='操作类型')),
                ('content', models.TextField(verbose_name='操作内容')),
                ('position', models.IntegerField(verbose_name='操作位置')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('revision', models.IntegerField(default=1, verbose_name='版本号')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_operations', to='note.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '编辑操作',
                'verbose_name_plural': '编辑操作历史',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeEditingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('cursor_position', models.IntegerField(default=0, verbose_name='光标位置')),
                ('selection_start', models.IntegerField(default=0, verbose_name='选择开始位置')),
                ('selection_end', models.IntegerField(default=0, verbose_name='选择结束位置')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_sessions', to='note.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '协同编辑会话',
                'verbose_name_plural': '协同编辑会话记录',
                'unique_together': {('note', 'user')},
            },
        ),
    ]
