# Generated by Django 4.2.7 on 2026-01-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editoperation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='editoperation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_collaborative',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_edit_time',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_editor',
        ),
        migrations.DeleteModel(
            name='CollaborativeEditingSession',
        ),
        migrations.DeleteModel(
            name='EditOperation',
        ),
    ]
