# Generated by Django 4.2.7 on 2026-01-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_note_collaborators_note_is_collaborative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='note.note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='note.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日记评论',
                'verbose_name_plural': '日记评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_likes', to='note.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日记点赞',
                'verbose_name_plural': '日记点赞',
                'unique_together': {('user', 'note')},
            },
        ),
    ]
