# Generated by Django 4.2.7 on 2026-01-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_achievements'),
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborativedocument',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
