# Generated by Django 4.2.7 on 2026-01-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('task', '任务'), ('challenge', '挑战'), ('adventure', '冒险')], max_length=20, verbose_name='游戏类型'),
        ),
    ]
