# Generated by Django 4.2.7 on 2026-01-20 16:03

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=articles.models.get_article_image_path, verbose_name='文章封面图')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '专栏文章',
                'verbose_name_plural': '专栏文章管理',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='专栏名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='专栏标识')),
                ('description', models.TextField(blank=True, null=True, verbose_name='专栏简介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=articles.models.get_column_cover_path, verbose_name='专栏封面图')),
                ('category', models.CharField(choices=[('love_growth', '恋爱成长手册'), ('diary_inspiration', '日记灵感库'), ('festival_special', '节日特辑'), ('platform_activity', '平台活动通知'), ('other', '其他')], max_length=50, verbose_name='专栏分类')),
                ('subscriber_count', models.IntegerField(default=0, verbose_name='订阅人数')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '官方专栏',
                'verbose_name_plural': '官方专栏管理',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.columnarticle', verbose_name='所属文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '专栏评论',
                'verbose_name_plural': '专栏评论管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='columnarticle',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.officialcolumn', verbose_name='所属专栏'),
        ),
        migrations.CreateModel(
            name='ColumnSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='是否订阅')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='articles.officialcolumn', verbose_name='订阅专栏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='订阅用户')),
            ],
            options={
                'verbose_name': '专栏订阅',
                'verbose_name_plural': '专栏订阅管理',
                'unique_together': {('user', 'column')},
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.columnarticle', verbose_name='所属文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞管理',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
