# Generated by Django 4.2.7 on 2026-01-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mall.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50, verbose_name='收件人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('detail_address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮政编码')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='mall_images/category/', verbose_name='分类图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mall.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('type', models.CharField(choices=[('满减券', '满减券'), ('折扣券', '折扣券'), ('现金券', '现金券')], max_length=20, verbose_name='优惠券类型')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠券价值')),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('remaining_quantity', models.IntegerField(default=0, verbose_name='剩余数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.BooleanField(default=False, verbose_name='活动状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '秒杀活动',
                'verbose_name_plural': '秒杀活动',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='轮播图标题')),
                ('image', models.ImageField(upload_to='mall_images/banner/%Y%m%d/', verbose_name='轮播图图片')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='跳转链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=mall.models.generate_order_number, max_length=50, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('delivered', '已收货'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('logistics_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='物流公司')),
                ('logistics_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='物流单号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='订单备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.address', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单项总价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mall.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('old_price', models.DecimalField(decimal_places=2, default=99, max_digits=10, verbose_name='商品原价')),
                ('main_image', models.ImageField(blank=True, upload_to='mall_images/product/main/%Y%m%d/', verbose_name='商品主图')),
                ('detail_image', models.ImageField(blank=True, upload_to='mall_images/product/detail/%Y%m%d/', verbose_name='详情图')),
                ('sku_image', models.ImageField(blank=True, upload_to='mall_images/product/sku/%Y%m%d/', verbose_name='SKU图')),
                ('rating', models.FloatField(default=0, verbose_name='商品评分')),
                ('num_reviews', models.IntegerField(default=0, verbose_name='评论数量')),
                ('monthly_sales', models.IntegerField(default=0, verbose_name='月销量')),
                ('product_stock', models.IntegerField(default=0, verbose_name='库存')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_couple_product', models.BooleanField(default=False, verbose_name='是否情侣款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.category', verbose_name='商品类别')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#333333', max_length=20, verbose_name='标签颜色')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='mall.coupon', verbose_name='优惠券')),
                ('used_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='mall.order', verbose_name='使用订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'ordering': ['-obtained_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('view', '浏览'), ('add_cart', '加入购物车'), ('mark', '收藏'), ('purchase', '购买')], max_length=20, verbose_name='行为类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='mall.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('reason', models.TextField(verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核拒绝'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='退款状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='mall.order', verbose_name='订单')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='mall.orderitem', verbose_name='订单项')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '退款申请',
                'verbose_name_plural': '退款申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规格名称')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='规格价格')),
                ('stock', models.IntegerField(default=0, verbose_name='规格库存')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mall_images/product/sku/', verbose_name='规格图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='mall.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(default=mall.models.generate_payment_number, max_length=50, unique=True, verbose_name='支付单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额')),
                ('method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('card', '银行卡')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方交易号')),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='退款交易号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mall.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.productsku', verbose_name='商品规格'),
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_company', models.CharField(max_length=100, verbose_name='物流公司')),
                ('logistics_no', models.CharField(max_length=50, verbose_name='物流单号')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('exception', '异常')], default='pending', max_length=20, verbose_name='物流状态')),
                ('latest_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='最新状态描述')),
                ('trajectory', models.TextField(blank=True, null=True, verbose_name='物流轨迹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='mall.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '物流信息',
                'verbose_name_plural': '物流信息',
            },
        ),
        migrations.CreateModel(
            name='ProductTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='mall.product', verbose_name='商品')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mall.producttag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '商品标签关联',
                'verbose_name_plural': '商品标签关联',
                'unique_together': {('product', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ProductMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='mall.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_marks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='秒杀价格')),
                ('flash_stock', models.IntegerField(default=0, verbose_name='秒杀库存')),
                ('limit_per_user', models.IntegerField(default=1, verbose_name='每人限购数量')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mall.flashsale', verbose_name='秒杀活动')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='mall.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '秒杀商品',
                'verbose_name_plural': '秒杀商品',
                'unique_together': {('flash_sale', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('selected', models.BooleanField(default=True, verbose_name='是否选中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product', verbose_name='商品')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.productsku', verbose_name='商品规格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车项',
                'verbose_name_plural': '购物车项',
                'unique_together': {('user', 'product', 'sku')},
            },
        ),
    ]
