# Generated by Django 4.2.7 on 2026-01-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('old_price', models.DecimalField(decimal_places=2, default=99, max_digits=10, verbose_name='商品原价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/id/', verbose_name='商品图片')),
                ('rating', models.FloatField(default=0, verbose_name='商品评分')),
                ('num_reviews', models.IntegerField(default=0, verbose_name='评论数量')),
                ('category', models.CharField(max_length=100, verbose_name='商品类别')),
                ('monthly_sales', models.IntegerField(default=0, verbose_name='月销量')),
                ('product_stock', models.IntegerField(default=0, verbose_name='库存')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
