# Generated by Django 4.2.7 on 2026-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='是否选中'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('card', '银行卡')], max_length=50, null=True, verbose_name='支付方式'),
        ),
    ]
