# Generated by Django 4.2.7 on 2026-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='是否新品'),
        ),
    ]
