# Generated by Django 4.2.7 on 2026-02-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='mall_images/active/', verbose_name='活动封面'),
        ),
    ]
