# Generated by Django 4.2.7 on 2026-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_flashsale_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='need_countdown',
            field=models.BooleanField(default=True, verbose_name='是否需要倒计时'),
        ),
    ]
