# Generated by Django 4.2.7 on 2026-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_flashsale_need_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='is_vip_only',
            field=models.BooleanField(default=False, verbose_name='是否仅VIP可见'),
        ),
    ]
