# Generated by Django 4.2.7 on 2026-01-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='动态内容')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('favorites', models.IntegerField(default=0, verbose_name='收藏数')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '社区动态',
                'verbose_name_plural': '社区动态',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MomentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moment_images/%Y/%m/%d/')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_images', to='moment.moment')),
            ],
        ),
        migrations.AddField(
            model_name='moment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='moments', to='moment.tag'),
        ),
        migrations.AddField(
            model_name='moment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='moment.moment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='moment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes', to='moment.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'moment')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_favorites', to='moment.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'moment')},
            },
        ),
    ]
