# Generated by Django 4.2.7 on 2026-02-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
