# Generated by Django 4.2.7 on 2026-01-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0002_moment_favorites_like_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='note',
        ),
    ]
