# Generated by Django 4.2.7 on 2026-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0003_remove_comment_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'verbose_name': '社区动态', 'verbose_name_plural': '社区动态'},
        ),
        migrations.AddField(
            model_name='moment',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
