# Generated by Django 4.2.7 on 2026-01-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('failed', '已失败')], default='pending', max_length=10, verbose_name='任务状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_shared', models.BooleanField(default=True, verbose_name='是否共享给伴侣')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情侣任务',
                'verbose_name_plural': '情侣任务管理',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='纪念日标题')),
                ('anniversary_date', models.DateField(verbose_name='纪念日日期')),
                ('anniversary_type', models.CharField(choices=[('love_start', '相恋日'), ('first_date', '第一次约会'), ('valentine', '情人节'), ('birthday_partner', '伴侣生日'), ('anniversary', '结婚纪念日'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='纪念日类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='纪念日描述')),
                ('is_reminder_enabled', models.BooleanField(default=True, verbose_name='启用提醒')),
                ('reminder_days', models.IntegerField(default=1, verbose_name='提前提醒天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '纪念日',
                'verbose_name_plural': '纪念日管理',
                'ordering': ['anniversary_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='couple.coupletask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '任务完成记录',
                'verbose_name_plural': '任务完成记录',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
