# Generated by Django 4.2.7 on 2026-01-22 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couple', '0002_quizcategory_quizquestion_userquizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouplePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('description', models.TextField(verbose_name='地点描述')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('place_type', models.CharField(choices=[('romantic', '浪漫约会'), ('outdoor', '户外探险'), ('cultural', '文化体验'), ('dining', '美食餐厅'), ('entertainment', '休闲娱乐'), ('free', '免费景点'), ('other', '其他')], max_length=20, verbose_name='地点类型')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('review_count', models.IntegerField(default=0, verbose_name='评价数量')),
                ('price_range', models.CharField(max_length=50, verbose_name='价格范围')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '情侣地点',
                'verbose_name_plural': '情侣地点管理',
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='歌曲标题')),
                ('artist', models.CharField(max_length=100, verbose_name='歌手')),
                ('album_cover', models.ImageField(blank=True, null=True, upload_to='music_covers/', verbose_name='专辑封面')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music_files/', verbose_name='音频文件')),
                ('is_currently_playing', models.BooleanField(default=False, verbose_name='是否正在播放')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoveStoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('date', models.DateField(verbose_name='事件日期')),
                ('image', models.ImageField(blank=True, null=True, upload_to='love_story_images/', verbose_name='事件图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_story_timeline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CoupleRelationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_history_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_history_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情侣关系历史',
                'verbose_name_plural': '情侣关系历史记录',
                'ordering': ['-ended_at'],
            },
        ),
        migrations.CreateModel(
            name='CoupleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='正确答案')),
                ('options', models.JSONField(verbose_name='选项列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
