# Generated by Django 4.2.7 on 2026-01-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0003_coupleplace_musicplayer_lovestorytimeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupleplace',
            name='image_url',
        ),
        migrations.AddField(
            model_name='coupleplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='couple/places_images/', verbose_name='地点图片'),
        ),
    ]
