# Generated by Django 4.2.7 on 2026-01-23 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couple', '0004_remove_coupleplace_image_url_coupleplace_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love_vow', models.TextField(blank=True, max_length=1000, null=True, verbose_name='爱情誓言')),
                ('relationship_start_date', models.DateField(verbose_name='相恋日期')),
                ('couple_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='情侣名')),
                ('love_story', models.TextField(blank=True, max_length=2000, null=True, verbose_name='恋爱故事')),
                ('theme', models.CharField(choices=[('light_love', '热恋粉紫'), ('dreamy_sky', '梦幻星空'), ('fresh_nature', '清新自然'), ('vibrant_orange', '活力橙红')], default='light_love', max_length=50, verbose_name='主题风格')),
                ('primary_color', models.CharField(default='#FF6B8B', max_length=20, verbose_name='主色调')),
                ('secondary_color', models.CharField(default='#722ED1', max_length=20, verbose_name='辅助色')),
                ('visibility', models.CharField(choices=[('only_me', '仅自己可见'), ('friends', '仅好友可见'), ('public', '所有人可见')], default='only_me', max_length=20, verbose_name='情侣关系可见性')),
                ('show_couple_dynamics', models.BooleanField(default=True, verbose_name='显示情侣动态')),
                ('show_anniversary', models.BooleanField(default=True, verbose_name='显示纪念日')),
                ('show_gifts', models.BooleanField(default=False, verbose_name='显示礼物记录')),
                ('notify_partner_messages', models.BooleanField(default=True, verbose_name='Ta的消息提醒')),
                ('notify_dynamics', models.BooleanField(default=True, verbose_name='动态提醒')),
                ('notify_anniversary', models.BooleanField(default=True, verbose_name='纪念日提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_relation_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_relation_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情侣关系',
                'verbose_name_plural': '情侣关系管理',
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
