# Generated by Django 4.2.7 on 2026-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0005_couplerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicplayer',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='外部音乐链接（如网易云音乐）'),
        ),
        migrations.AlterField(
            model_name='lovestorytimeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='couple/love_story_images/', verbose_name='事件图片'),
        ),
        migrations.AlterField(
            model_name='musicplayer',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='couple/music_images/', verbose_name='专辑封面'),
        ),
        migrations.AlterField(
            model_name='musicplayer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='couple/music_files/', verbose_name='音频文件'),
        ),
    ]
