# Generated by Django 4.2.7 on 2026-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('status', models.CharField(choices=[('active', '进行中'), ('upcoming', '即将开始'), ('ended', '已结束')], default='upcoming', max_length=20, verbose_name='活动状态')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='活动图片URL')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动地点')),
                ('participant_count', models.IntegerField(default=0, verbose_name='参与人数')),
                ('prize_info', models.TextField(blank=True, null=True, verbose_name='奖品信息')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社区活动',
                'verbose_name_plural': '社区活动',
                'db_table': 'sys_community_active',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
