# Generated by Django 4.2.7 on 2026-01-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityevent',
            name='image_url',
        ),
        migrations.AddField(
            model_name='communityevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sys_images/community/community_active_images/', verbose_name='活动图片'),
        ),
    ]
