# Generated by Django 5.2.4 on 2025-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=10, verbose_name='商品原价'),
        ),
    ]
