# Generated by Django 5.2.4 on 2025-07-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='couple',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='App.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='couple_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='情侣邀请码'),
        ),
        migrations.AddField(
            model_name='profile',
            name='couple_joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='绑定时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='couple_pending',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_partner', to='App.profile'),
        ),
    ]
