# Generated by Django 5.2 on 2025-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_moment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ['-created_at'], 'verbose_name': '情侣动态', 'verbose_name_plural': '情侣动态'},
        ),
        migrations.AlterField(
            model_name='moment',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='moment_images/%Y/%m/%d/', verbose_name='动态图片'),
        ),
    ]
