# Generated by Django 5.2.4 on 2025-07-30 03:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_collaborativedocument_documentoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=1000, verbose_name='日记内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('mood', models.CharField(choices=[('happy', '开心'), ('heart', '心动'), ('laugh', '欢乐'), ('sad', '难过'), ('angry', '生气')], default='happy', max_length=10, verbose_name='心情')),
                ('is_shared', models.BooleanField(default=False, verbose_name='是否共享')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note_likes', to='App.note'),
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteimage', models.ImageField(upload_to='note_images/%Y/%m/%d/', verbose_name='日记图片')),
                ('notemoment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_images', to='App.note')),
            ],
        ),
    ]
