# Generated by Django 5.2 on 2025-05-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_moment_options_alter_moment_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={},
        ),
        migrations.RemoveField(
            model_name='moment',
            name='images',
        ),
        migrations.CreateModel(
            name='MomentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moment_images/%Y/%m/%d/')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_images', to='App.moment')),
            ],
        ),
    ]
