# Generated by Django 5.2 on 2025-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_moment_options_remove_moment_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='comments',
            field=models.IntegerField(db_default=0, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='likes',
            field=models.IntegerField(db_default=0, default=0, verbose_name='点赞数'),
        ),
    ]
