# Generated by Django 5.2.4 on 2025-08-07 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_note_comment_note_noteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mood',
            field=models.CharField(choices=[('happy', '开心'), ('heart', '心动'), ('laugh', '欢乐'), ('sad', '难过'), ('angry', '生气'), ('calm', '平静')], default='happy', max_length=10, verbose_name='心情'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
