# Generated by Django 5.2 on 2025-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_moment_comments_alter_moment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='moment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='moments', to='App.tag'),
        ),
    ]
