# Generated by Django 5.2.4 on 2025-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_note_mood_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
    ]
