# Generated by Django 5.2.4 on 2025-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/id/', verbose_name='商品图片'),
        ),
    ]
