# Generated by Django 5.2 on 2025-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_tag_moment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAvatar',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='userAvatar/%Y/%m/%d/'),
        ),
    ]
