# Generated by Django 5.2 on 2025-05-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_user_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='userAvatar/'),
        ),
    ]
