# Generated by Django 5.2 on 2025-05-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userAvatar',
        ),
    ]
