# Generated by Django 5.2 on 2025-05-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_profile_options_remove_profile_useravatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='userAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='userAvatar/'),
        ),
    ]
