# Generated by Django 5.2 on 2025-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_profile_avatar_image_profile_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('北京市', '北京市'), ('天津市', '天津市'), ('重庆市', '重庆市'), ('上海市', '上海市')], max_length=100, null=True, verbose_name='所在地'),
        ),
    ]
