# Generated by Django 5.2 on 2025-05-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
