# Generated by Django 5.2.3 on 2025-07-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='用户名', max_length=30),
        ),
    ]
