# Generated by Django 4.2.7 on 2026-01-21 13:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='手机号')),
                ('name', models.CharField(default='用户名', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone_verified', models.BooleanField(default=False, verbose_name='手机号已验证')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='成就标题')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('icon', models.CharField(max_length=10, verbose_name='成就图标')),
                ('requirement', models.CharField(max_length=200, verbose_name='解锁要求')),
                ('category', models.CharField(max_length=50, verbose_name='成就分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就管理',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CouplePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('description', models.TextField(verbose_name='地点描述')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('place_type', models.CharField(choices=[('restaurant', '餐厅'), ('cafe', '咖啡馆'), ('park', '公园'), ('movie', '电影院'), ('museum', '博物馆'), ('activity', '活动场所'), ('other', '其他')], max_length=20, verbose_name='地点类型')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('review_count', models.IntegerField(default=0, verbose_name='评价数量')),
                ('price_range', models.CharField(max_length=50, verbose_name='价格范围')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '情侣地点',
                'verbose_name_plural': '情侣地点管理',
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', '手机号'), ('email', '邮箱')], max_length=10, verbose_name='验证类型')),
                ('target', models.CharField(max_length=50, verbose_name='目标')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='特权名称')),
                ('description', models.TextField(verbose_name='特权描述')),
                ('required_level', models.CharField(choices=[('normal', 'Ⅰ'), ('bronze', 'Ⅱ'), ('silver', 'Ⅲ'), ('diamond', 'Ⅳ'), ('king', 'Ⅴ'), ('god', 'Ⅵ')], max_length=20, verbose_name='所需VIP等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'VIP特权',
                'verbose_name_plural': 'VIP特权管理',
                'ordering': ['-required_level'],
            },
        ),
        migrations.CreateModel(
            name='VIPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='充值金额')),
                ('duration', models.IntegerField(verbose_name='充值时长(天)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'VIP充值订单',
                'verbose_name_plural': 'VIP充值订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('normal', 'Ⅰ'), ('bronze', 'Ⅱ'), ('silver', 'Ⅲ'), ('diamond', 'Ⅳ'), ('king', 'Ⅴ'), ('god', 'Ⅵ')], default='normal', max_length=20, verbose_name='VIP等级')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开通时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='续费次数')),
                ('total_recharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='累计充值金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP会员',
                'verbose_name_plural': 'VIP会员管理',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAvatar', models.ImageField(blank=True, default='userAvatar/OIP-C.jpg', null=True, upload_to='userAvatar/')),
                ('gender', models.CharField(choices=[('female', '女'), ('male', '男'), ('other', '保密')], default='other', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('location', models.CharField(blank=True, choices=[('北京市', '北京市'), ('天津市', '天津市'), ('重庆市', '重庆市'), ('上海市', '上海市')], max_length=100, null=True, verbose_name='所在地')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('couple_joined_at', models.DateTimeField(blank=True, null=True, verbose_name='绑定时间')),
                ('couple_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='情侣邀请码')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='开启通知声音')),
                ('notification_vibration', models.BooleanField(default=True, verbose_name='开启震动提醒')),
                ('do_not_disturb', models.BooleanField(default=False, verbose_name='夜间免打扰')),
                ('couple_messages', models.BooleanField(default=True, verbose_name='情侣消息通知')),
                ('community_messages', models.BooleanField(default=True, verbose_name='社区消息通知')),
                ('system_messages', models.BooleanField(default=True, verbose_name='系统消息通知')),
                ('comments_replies', models.BooleanField(default=True, verbose_name='评论和回复通知')),
                ('likes_favorites', models.BooleanField(default=True, verbose_name='点赞和收藏通知')),
                ('anniversary_reminders', models.BooleanField(default=True, verbose_name='纪念日提醒')),
                ('couple_activity_recommendations', models.BooleanField(default=True, verbose_name='情侣活动推荐')),
                ('hot_topic_reminders', models.BooleanField(default=False, verbose_name='热门话题提醒')),
                ('promotion_push', models.BooleanField(default=False, verbose_name='优惠活动推送')),
                ('profile_visibility', models.CharField(choices=[('everyone', '所有人可见'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='everyone', max_length=20, verbose_name='个人主页可见性')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='显示在线状态')),
                ('allow_search', models.BooleanField(default=True, verbose_name='允许被搜索')),
                ('show_location', models.BooleanField(default=False, verbose_name='显示地理位置')),
                ('moments_visibility', models.CharField(choices=[('everyone', '所有人可见'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='everyone', max_length=20, verbose_name='动态可见性')),
                ('album_visibility', models.CharField(choices=[('everyone', '所有人可见'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='friends', max_length=20, verbose_name='相册可见性')),
                ('two_factor_auth', models.BooleanField(default=False, verbose_name='双因素认证')),
                ('login_notification', models.BooleanField(default=True, verbose_name='登录通知')),
                ('session_management', models.BooleanField(default=True, verbose_name='会话管理')),
                ('theme', models.CharField(choices=[('light', '浅色主题'), ('dark', '深色主题'), ('system', '跟随系统')], default='light', max_length=20, verbose_name='主题')),
                ('font_size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=20, verbose_name='字体大小')),
                ('interface_style', models.CharField(choices=[('modern', '现代'), ('classic', '经典')], default='modern', max_length=20, verbose_name='界面风格')),
                ('couple', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='core.profile')),
                ('couple_pending', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_partner', to='core.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
            },
        ),
        migrations.CreateModel(
            name='MusicPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='歌曲标题')),
                ('artist', models.CharField(max_length=100, verbose_name='歌手')),
                ('album_cover', models.ImageField(blank=True, null=True, upload_to='music_covers/', verbose_name='专辑封面')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music_files/', verbose_name='音频文件')),
                ('is_currently_playing', models.BooleanField(default=False, verbose_name='是否正在播放')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoveStoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('date', models.DateField(verbose_name='事件日期')),
                ('image', models.ImageField(blank=True, null=True, upload_to='love_story_images/', verbose_name='事件图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_story_timeline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CoupleRelationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_history_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_history_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情侣关系历史',
                'verbose_name_plural': '情侣关系历史记录',
                'ordering': ['-ended_at'],
            },
        ),
        migrations.CreateModel(
            name='CoupleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='正确答案')),
                ('options', models.JSONField(verbose_name='选项列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='是否解锁')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='解锁时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='core.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就管理',
                'ordering': ['-unlocked_at', '-updated_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
