# Generated by Django 4.2.7 on 2026-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupleplace',
            name='place_type',
            field=models.CharField(choices=[('romantic', '浪漫约会'), ('outdoor', '户外探险'), ('cultural', '文化体验'), ('dining', '美食餐厅'), ('entertainment', '休闲娱乐'), ('free', '免费景点'), ('other', '其他')], max_length=20, verbose_name='地点类型'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userAvatar',
            field=models.ImageField(blank=True, default='userAvatar/defult_user.png', null=True, upload_to='userAvatar/'),
        ),
    ]
