# Generated by Django 4.2.7 on 2026-01-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coupleplace_place_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouplePlace',
        ),
        migrations.RemoveField(
            model_name='couplerelationhistory',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='couplerelationhistory',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='lovestorytimeline',
            name='user',
        ),
        migrations.RemoveField(
            model_name='musicplayer',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoupleQuiz',
        ),
        migrations.DeleteModel(
            name='CoupleRelationHistory',
        ),
        migrations.DeleteModel(
            name='LoveStoryTimeline',
        ),
        migrations.DeleteModel(
            name='MusicPlayer',
        ),
    ]
