# Generated by Django 4.2.7 on 2026-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_musicplayer_lovestorytimeline_couplequiz_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='album_visibility',
            field=models.CharField(choices=[('everyone', '所有人可见'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='friends', max_length=20, verbose_name='相册可见性'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_search',
            field=models.BooleanField(default=True, verbose_name='允许被搜索'),
        ),
        migrations.AddField(
            model_name='profile',
            name='anniversary_reminders',
            field=models.BooleanField(default=True, verbose_name='纪念日提醒'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comments_replies',
            field=models.BooleanField(default=True, verbose_name='评论和回复通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='community_messages',
            field=models.BooleanField(default=True, verbose_name='社区消息通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='couple_activity_recommendations',
            field=models.BooleanField(default=True, verbose_name='情侣活动推荐'),
        ),
        migrations.AddField(
            model_name='profile',
            name='couple_messages',
            field=models.BooleanField(default=True, verbose_name='情侣消息通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='do_not_disturb',
            field=models.BooleanField(default=False, verbose_name='夜间免打扰'),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=20, verbose_name='字体大小'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hot_topic_reminders',
            field=models.BooleanField(default=False, verbose_name='热门话题提醒'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interface_style',
            field=models.CharField(choices=[('modern', '现代'), ('classic', '经典')], default='modern', max_length=20, verbose_name='界面风格'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_favorites',
            field=models.BooleanField(default=True, verbose_name='点赞和收藏通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_notification',
            field=models.BooleanField(default=True, verbose_name='登录通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='moments_visibility',
            field=models.CharField(choices=[('everyone', '所有人可见'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='everyone', max_length=20, verbose_name='动态可见性'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_sound',
            field=models.BooleanField(default=True, verbose_name='开启通知声音'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_vibration',
            field=models.BooleanField(default=True, verbose_name='开启震动提醒'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('everyone', '所有人可见'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='everyone', max_length=20, verbose_name='个人主页可见性'),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotion_push',
            field=models.BooleanField(default=False, verbose_name='优惠活动推送'),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_management',
            field=models.BooleanField(default=True, verbose_name='会话管理'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_location',
            field=models.BooleanField(default=False, verbose_name='显示地理位置'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online_status',
            field=models.BooleanField(default=True, verbose_name='显示在线状态'),
        ),
        migrations.AddField(
            model_name='profile',
            name='system_messages',
            field=models.BooleanField(default=True, verbose_name='系统消息通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', '浅色主题'), ('dark', '深色主题'), ('system', '跟随系统')], default='light', max_length=20, verbose_name='主题'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_auth',
            field=models.BooleanField(default=False, verbose_name='双因素认证'),
        ),
    ]
