# Generated by Django 4.2.7 on 2026-01-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_coupleplace_and_more'),
    ]

    operations = [
    ]
