# Generated by Django 4.2.7 on 2026-01-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260123_0043'),
    ]

    operations = [
    ]
