# Generated by Django 4.2.7 on 2026-01-12 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_verificationcode_user_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='特权名称')),
                ('description', models.TextField(verbose_name='特权描述')),
                ('required_level', models.CharField(choices=[('normal', '普通会员'), ('bronze', '青铜VIP'), ('silver', '白银VIP'), ('gold', '黄金VIP'), ('platinum', '铂金VIP'), ('diamond', '钻石VIP')], max_length=20, verbose_name='所需VIP等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'VIP特权',
                'verbose_name_plural': 'VIP特权管理',
                'ordering': ['-required_level'],
            },
        ),
        migrations.CreateModel(
            name='VIPMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('normal', '普通会员'), ('bronze', '青铜VIP'), ('silver', '白银VIP'), ('gold', '黄金VIP'), ('platinum', '铂金VIP'), ('diamond', '钻石VIP')], default='normal', max_length=20, verbose_name='VIP等级')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开通时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='续费次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP会员',
                'verbose_name_plural': 'VIP会员管理',
                'ordering': ['-level'],
            },
        ),
    ]
