# Generated by Django 4.2.7 on 2026-01-15 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vipprivilege_vipmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='充值金额')),
                ('duration', models.IntegerField(verbose_name='充值时长(天)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'VIP充值订单',
                'verbose_name_plural': 'VIP充值订单管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
