# Generated by Django 4.2.7 on 2026-01-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260123_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIPMember',
        ),
        migrations.DeleteModel(
            name='VIPOrder',
        ),
        migrations.DeleteModel(
            name='VIPPrivilege',
        ),
    ]