# Generated by Django 4.2.7 on 2026-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_viporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipmember',
            name='total_recharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='累计充值金额'),
        ),
    ]
