# Generated by Django 4.2.7 on 2026-01-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_vip_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]