# Generated by Django 4.2.7 on 2026-02-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interface_style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
