# Generated by Django 4.2.7 on 2026-01-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vipmember_total_recharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
