# Generated by Django 4.2.7 on 2026-01-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='成就标题')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('icon', models.CharField(max_length=10, verbose_name='成就图标')),
                ('requirement', models.CharField(max_length=200, verbose_name='解锁要求')),
                ('category', models.CharField(max_length=50, verbose_name='成就分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就管理',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='是否解锁')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='解锁时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='core.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就管理',
                'ordering': ['-unlocked_at', '-updated_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
