# Generated by Django 4.2.7 on 2026-01-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coupleplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at'], 'verbose_name': '关注关系', 'verbose_name_plural': '关注关系'},
        ),
    ]
